export interface StudentProfile {
  id?: number;
  user_id: number;
  iin: string;
  student_id: string;
  faculty?: string;
  specialist?: string;
  course?: number;
  year_of_study?: number;
  enrollment_year?: string;
  enrollment_date?: string;
  blood_type?: string;
  violations?: string;
  parent_name?: string;
  parent_phone?: string;
  parent_email?: string;
  guardian_name?: string;
  guardian_phone?: string;
  mentor_name?: string;
  mentor_email?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  emergency_contact_relationship?: string;
  medical_conditions?: string;
  dietary_restrictions?: string;
  program?: string;
  year_level?: number;
  nationality?: string;
  deal_number?: string;
  agree_to_dormitory_rules?: boolean;
  has_meal_plan?: boolean;
  registration_limit_reached?: boolean;
  is_backup_list?: boolean;
  date_of_birth?: string;
  gender?: 'male' | 'female' | 'other';
  files?: any;
  city_id?: number;
  created_at?: string;
  updated_at?: string;
  [key: string]: any;
} 